language: scala
sudo: required
dist: trusty

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM;
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.10.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION hygiene/compile;
    else echo "Skipping hygiene on 2.10 (see \#300)";
    fi
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.12.* ]];
    then
      if [[ "$TRAVIS_SCALA_VERSION" != 2.10.* ]] && [[ "$TRAVIS_JDK_VERSION" == *jdk8* ]];
      then
        sbt ++$TRAVIS_SCALA_VERSION spray/test benchmark/test coverageReport && codecov;
      else
        sbt ++$TRAVIS_SCALA_VERSION spray/test;
      fi;
    else echo "Skipping Spray tests on 2.12";
    fi
  - if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
    else echo "Skipping Scala.js build";
    fi

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
