language: scala

scala:
  - 2.10.5
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  if [[ "$TRAVIS_BRANCH" == "scalajs" ]];
    then sbt ++$TRAVIS_SCALA_VERSION coreJS/test &&
      sbt ++$TRAVIS_SCALA_VERSION genericJS/test;
    else sbt ++$TRAVIS_SCALA_VERSION clean coverage validateJVM &&
      sbt ++$TRAVIS_SCALA_VERSION coverageAggregate;
  fi

after_success: bash <(curl -s https://codecov.io/bash)
